In [1]:
# Import da biblioteca numpy
import numpy as np

In [2]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [3]:
# Criando um arrey 1d
l = [1, 2, 3]
x = np.array(l)
print('x:', x)
print('shape:', x.shape)

x: [1 2 3]
shape: (3,)


In [4]:
# Criando um array 2d: listas aninhadas
l = [[1, 2], [3, 4]]
x = np.array(l)
print('x:\n', x)
print('shape:', x.shape)

x:
 [[1 2]
 [3 4]]
shape: (2, 2)


In [5]:
# Array contento apenas 0
dim = (2, 2) # linhas colunas
x = np.zeros(dim)
print(x)

[[0. 0.]
 [0. 0.]]


In [6]:
# Crianco array contendo apenas 1
size = (4, 4) # Linhas colunas
x = np.ones(size)
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# Criando valores dentro de um intervalo
# Valores uniformes entre 5 e 15
x_min, x_max = 5, 15
x = np.linspace(start=x_min, stop=x_max, num=6)
print(x)

[ 5.  7.  9. 11. 13. 15.]


In [8]:
# Criando matriz identidade
n = 4
x = np.eye(n)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
# Criando valores aleatorios
# np.random.seed(10)
x = np.random.random(size=(2, 3))
x

array([[0.21526673, 0.57557472, 0.93881644],
       [0.69601333, 0.94016311, 0.57465083]])

## Indexação de Arrays